# JET static-analysis tests for TransmissionLinelist.
#
# Pattern adapted from EpiAware/CensoredDistributions.jl
# (test/jet/runtests.jl and test/package/CodeLinting.jl). That package
# runs `JET.report_package` against the package module with
# `target_modules` set to the package itself so that warnings stay
# restricted to first-party code and ignore noise from upstream deps.
#
# JET cannot statically prove that variables bound by Turing's `~`
# rewriter exist, so every method generated by an `@model` macro
# triggers `UndefVarErrorReport` / `MethodErrorReport` false positives.
# These are recognisable because the method signature contains
# `DynamicPPL.Model` (the rewriter inserts it as the first argument).
# We filter them out after `report_package` returns and `@test` that no
# real reports remain.
#
# JET on pre-release Julia is flaky so this testset is skipped there,
# matching the upstream pattern.

using JET

# Return `true` if the report originates inside a Turing `@model`-rewritten
# method. These method instances are generated by the `@model` macro and
# always take `DynamicPPL.Model` and `DynamicPPL.AbstractVarInfo` as the
# first two positional arguments, which JET cannot follow statically.
function _is_turing_model_frame(report)
    isempty(report.vst) && return false
    mi = report.vst[1].linfo
    mi isa Core.MethodInstance || return false
    return occursin("DynamicPPL.Model", string(mi.specTypes))
end

@testset "JET static analysis" begin
    if VERSION >= v"1.10" && VERSION < v"1.13" &&
       get(ENV, "JULIA_CI_EXPERIMENTAL", "false") != "true"
        rep = JET.report_package(
            TransmissionLinelist;
            target_modules = (TransmissionLinelist,)
        )
        reports = filter(!_is_turing_model_frame, JET.get_reports(rep))
        if !isempty(reports)
            @info "JET found $(length(reports)) unfiltered report(s)"
            for r in reports
                show(stdout, MIME"text/plain"(), r)
                println()
            end
        end
        @test isempty(reports)
    else
        @info "Skipping JET tests" VERSION experimental = get(
            ENV, "JULIA_CI_EXPERIMENTAL", "false"
        )
        @test_skip "JET skipped on experimental Julia"
    end
end
