# JET static-analysis tests for TransmissionLinelist.
#
# Pattern adapted from EpiAware/CensoredDistributions.jl
# (test/jet/runtests.jl and test/package/CodeLinting.jl). That package
# runs `JET.report_package` against the package module with
# `target_modules` set to the package itself so warnings stay
# restricted to first-party code and ignore noise from upstream deps.
#
# What this file checks:
#
# 1. `report_package` (JETAnalyzer) — correctness: undef-vars and
#    no-method dispatches across user-written code in
#    `TransmissionLinelist`.
# 2. `report_opt` (OptAnalyzer) — runtime-dispatch (type-instability)
#    hotspots on a curated list of public + internal entry points that
#    must stay type-stable.
#
# What this file ignores, and why:
#
# - Reports from Turing's `@model`-rewritten methods. The `~` rewriter
#   inserts the RHS into a `let` block whose local bindings JET cannot
#   follow statically. Every such method emits spurious
#   `UndefVarErrorReport` and `MethodErrorReport`. We narrow the filter
#   to *only* those two report kinds, and *only* when the offending
#   method takes `DynamicPPL.Model` and `DynamicPPL.AbstractVarInfo` as
#   its first two arguments (i.e. it is unambiguously a
#   `@model`-rewritten method). Other report kinds on those same
#   methods still surface.
#
# - The quadrature path through `Integrals.IntegralProblem` /
#   `Integrals.solve` is type-unstable upstream: SciMLBase's `solve`
#   returns `Any`, so its result flowing through `_convolved_delays_cdf`
#   and the `Distributions.cdf(::ConvolvedDelays, ..)` methods picks up
#   ~19 `RuntimeDispatchReport`s. Asserting a concrete return type
#   would break AD (Mooncake/ForwardDiff need `solve` to return their
#   `Dual` tangent types). The instability is documented as expected
#   and those entry points are deliberately omitted from the curated
#   `report_opt` list below. See
#   https://github.com/SciML/SciMLBase.jl for ongoing inference work.
#
# JET on pre-release Julia is flaky so the testset is skipped there.

using JET
using Dates: Date
using Distributions: Normal
using Random: MersenneTwister

# Return `true` if `report` is an `UndefVarError` / `MethodError` report
# from a Turing `@model`-rewritten method. These method instances are
# generated by the `@model` macro and take `DynamicPPL.Model` and
# `DynamicPPL.AbstractVarInfo` as the first two positional arguments,
# which JET cannot follow statically. We deliberately narrow on report
# kind so non-rewrite issues (e.g. `RuntimeDispatchReport`) on
# `@model` methods still surface.
function _is_turing_rewrite_noise(report)
    report isa JET.UndefVarErrorReport ||
        report isa JET.MethodErrorReport ||
        return false
    isempty(report.vst) && return false
    mi = report.vst[1].linfo
    mi isa Core.MethodInstance || return false
    return occursin("DynamicPPL.Model", string(mi.specTypes))
end

# Curated list of `(callable, argtypes)` pairs that must stay
# type-stable. Each entry has zero `report_opt` reports against the
# OptAnalyzer at the time of writing. Adding a new entry here pins
# a hot path; removing one needs a justifying comment.
const _REPORT_OPT_CALLS = [
    # Pure interpolation / R(t) evaluation along onset offsets.
    (TransmissionLinelist.log_R_at,
        (Float64, Vector{Float64}, Vector{Float64})),
    (TransmissionLinelist._R_at_onsets,
        (Vector{Float64}, Vector{Float64}, Vector{Float64})),
    # All four `_intervention_offsets` method dispatches: nothing,
    # single Date, vector of Dates, and the internal NaturalChain
    # marker.
    (TransmissionLinelist._intervention_offsets,
        (Nothing, Float64, Vector{Float64}, Date, Int)),
    (TransmissionLinelist._intervention_offsets,
        (Date, Float64, Vector{Float64}, Date, Int)),
    (TransmissionLinelist._intervention_offsets,
        (Vector{Date}, Float64, Vector{Float64}, Date, Int)),
    (TransmissionLinelist._intervention_offsets,
        (TransmissionLinelist.NaturalChain,
            Float64, Vector{Float64}, Date, Int)),
    # Inner integrand of the convolved-delays quadrature. The outer
    # `solve` call is type-unstable upstream (SciMLBase) but the
    # integrand itself must stay stable.
    (TransmissionLinelist._convolved_delays_integrand,
        (Float64,
            NamedTuple{
                (:centre, :halfwidth, :x, :inc_dist, :δ_dist),
                Tuple{Float64, Float64, Vector{Float64},
                    Normal{Float64}, Normal{Float64}}})),
    # Predictive draw used inside the per-source future-onset loop.
    (TransmissionLinelist.posterior_predictive,
        (typeof(TransmissionLinelist.case_model),
            MersenneTwister, Float64, Int,
            Float64, Float64, Float64)),
    # Post-processing helpers.
    (TransmissionLinelist.qci, (Vector{Float64},)),
    (TransmissionLinelist.summarise_predictive, (Vector{Float64},)),
    # Real-time prep.
    (TransmissionLinelist.prepare_rt_edges, (Date,))
]

@testset "JET static analysis" begin
    if VERSION >= v"1.10" && VERSION < v"1.13" &&
       get(ENV, "JULIA_CI_EXPERIMENTAL", "false") != "true"
        @testset "report_package (correctness)" begin
            rep = JET.report_package(
                TransmissionLinelist;
                target_modules = (TransmissionLinelist,)
            )
            reports = filter(
                !_is_turing_rewrite_noise, JET.get_reports(rep)
            )
            if !isempty(reports)
                @info "JET found $(length(reports)) unfiltered report(s)"
                for r in reports
                    show(stdout, MIME"text/plain"(), r)
                    println()
                end
            end
            @test isempty(reports)
        end

        @testset "report_opt (type stability)" begin
            for (f, argtypes) in _REPORT_OPT_CALLS
                rep = JET.report_opt(f, argtypes)
                reports = JET.get_reports(rep)
                if !isempty(reports)
                    @info "report_opt found $(length(reports)) " *
                          "report(s) for $f"
                    for r in reports
                        show(stdout, MIME"text/plain"(), r)
                        println()
                    end
                end
                @test isempty(reports)
            end
        end
    else
        @info "Skipping JET tests" VERSION experimental = get(
            ENV, "JULIA_CI_EXPERIMENTAL", "false"
        )
        @test_skip "JET skipped on experimental Julia"
    end
end
